FROM alpine:3.11


# Add the hello-docker entrypoint
COPY entrypoint.sh /entrypoint.sh


ENTRYPOINT [ '/entrypoint.sh' ]

# nos vamos tratar a saida do script no entropoint
# entao nao precisa de um arquivo de saida

# CMD ['iwojd']